<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { service } from '../services/api'
const route=useRoute(),router=useRouter(); const editing=Boolean(route.params.id),saving=ref(false),error=ref(''); const form=reactive({title:'',content:'',password:String(route.query.password||'')})
onMounted(async()=>{if(editing){try{const data=await service.post(route.params.id,{countView:false});Object.assign(form,{title:data.title,content:data.content})}catch(e){alert(e.userMessage||e.message);router.push('/board')}}})
async function submit(){error.value='';saving.value=true;try{if(editing){await service.updatePost(route.params.id,form);router.push(`/board/${route.params.id}`)}else{const data=await service.createPost(form);router.push(data?.id?`/board/${data.id}`:'/board')}}catch(e){error.value=e.userMessage||e.response?.data?.detail||e.message||'저장에 실패했습니다.'}finally{saving.value=false}}
</script>
<template><section class="form-page"><div class="breadcrumb"><router-link to="/board">커뮤니티</router-link><span>›</span><span>{{editing?'게시글 수정':'글쓰기'}}</span></div><div class="page-heading"><span class="eyebrow">WRITE A STORY</span><h1>{{editing?'게시글 수정':'여행 이야기 작성'}}</h1><p>개인정보가 포함되지 않도록 주의해 주세요.</p></div><form class="post-form" @submit.prevent="submit"><label>제목<input v-model.trim="form.title" required maxlength="200" placeholder="제목을 입력하세요"/></label><label>내용<textarea v-model.trim="form.content" required rows="12" placeholder="여행 경험이나 유용한 정보를 작성해 주세요"></textarea></label><label>수정·삭제용 비밀번호<input v-model="form.password" type="password" required minlength="4" placeholder="4자 이상 입력하세요"/><small>회원 인증 대신 게시글 수정과 삭제에 사용됩니다.</small></label><p v-if="error" class="form-error" role="alert">{{error}}</p><div class="form-actions"><button type="button" class="button ghost dark" @click="router.back()">취소</button><button class="button" :disabled="saving">{{saving?'저장 중…':editing?'수정 완료':'등록'}}</button></div></form></section></template>
