<script setup>
import { nextTick, ref } from 'vue'; import { service } from '../services/api'
const open=ref(false),input=ref(''),loading=ref(false),body=ref(null)
const messages=ref([{role:'assistant',content:'안녕하세요. 대전 관광지, 맛집, 축제와 여행 코스를 물어보세요.'}])
const questions=['대전 관광지 추천해 줘','대전 맛집 알려 줘','이번 달 축제 알려 줘','커뮤니티에서 여행 코스 찾아 줘']
async function send(value){const message=(value??input.value).trim();if(!message||loading.value)return;const history=messages.value.map(({role,content})=>({role,content}));messages.value.push({role:'user',content:message});input.value='';loading.value=true;try{const data=await service.chat(message,history);messages.value.push({role:'assistant',content:data.answer||data.message||data.content||'답변을 확인하지 못했습니다.'})}catch(e){messages.value.push({role:'assistant',content:e.userMessage||'답변을 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.'})}finally{loading.value=false;await nextTick();body.value?.scrollTo({top:body.value.scrollHeight,behavior:'smooth'})}}
function keydown(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}if(e.key==='Escape')open.value=false}
</script>
<template><button v-if="!open" class="chat-fab" @click="open=true" aria-label="챗봇 열기">💬<span>여행 챗봇</span></button><section v-else class="chat-panel" aria-label="여행 챗봇" @keydown="keydown"><header><div><strong>대전 여행 챗봇</strong><small>공공데이터 기반 안내</small></div><button @click="open=false" aria-label="챗봇 닫기">×</button></header><div ref="body" class="chat-body"><div class="quick-questions"><button v-for="q in questions" :key="q" :disabled="loading" @click="send(q)">{{q}}</button></div><div v-for="(m,i) in messages" :key="i" :class="['bubble',m.role==='assistant'?'bot':'user']">{{m.content}}</div><div v-if="loading" class="bubble bot">답변을 찾는 중입니다…</div></div><form class="chat-input" @submit.prevent="send()"><label class="sr-only" for="chat-message">메시지</label><textarea id="chat-message" v-model="input" rows="1" placeholder="대전 여행에 대해 물어보세요" @keydown="keydown"></textarea><button :disabled="loading||!input.trim()">전송</button></form></section></template>
